### ISSUE TITLE
michaelsmith213 want to join pranaOS

### ISSUE THREAD

**Issue by michaelsmith213** [pranaOS/pranaOS#2]
hi @krishpranav I am experienced in c++ for couple of years I want to contribute to you. can I join

**Comment by krishpranav** [comment]
hi @michaelsmith213

**Comment by michaelsmith213** [comment]
hi

**Comment by krishpranav** [comment]
so you want to join pranaOS?? and help us to create pranaOS?

**Comment by michaelsmith213** [comment]
yes I am intrested

**Comment by michaelsmith213** [comment]
I saw your project in GitHub explore now only I created GitHub account

**Comment by michaelsmith213** [comment]
before I was using gitlab

**Comment by krishpranav** [comment]
ok @michaelsmith213

**Comment by krishpranav** [comment]
how many years your experienced in c++?

**Comment by michaelsmith213** [comment]
1 - 2 years

**Comment by krishpranav** [comment]
ok your selected

**Comment by michaelsmith213** [comment]
thanks
