### ISSUE TITLE
johnsmith5c12 wants to join pranaOS

### ISSUE THREAD

**Issue by johnsmith5c12** [pranaOS/pranaOS#31]

**Comment by johnsmith5c12** [comment]
hi sir I am specialist at python, typescript, c, c++

**Comment by krishpranav** [comment]
hi @johnsmith5c12 can you message me in discord we can discuss there

**Comment by johnsmith5c12** [comment]
ok sure sir

**Comment by johnsmith5c12** [comment]
can you provide the invite link sir

**Comment by krishpranav** [comment]
yes one second

**Comment by krishpranav** [comment]
here is the invitation link: https://discord.gg/XmpBTmy9Bz

**Comment by johnsmith5c12** [comment]
ok sir I will join
