### ISSUE TITLE
Aspect-Kraken wants to join pranaOS

### ISSUE THREAD

**Issue by Aspect-Kraken** [pranaOS/pranaOS#42]
Hi sir,
My name is John

so i want to join your effort 
My skills:
```
python - 2 years,
c++ - 1.5 years
c - 1 year
```
can i join pranaOS?

**Comment by krishpranav** [comment]
hey hi @Aspect-Kraken can you come to discord server?
discord link: https://discord.gg/XmpBTmy9Bz

**Comment by Aspect-Kraken** [comment]
ok sure sir
