### ISSUE TITLE
stevanson want's to join pranaOS

### ISSUE THREAD

**Issue by stevanson** [pranaOS/pranaOS#50]
To:
Author / Founder

Hi sir,
       I want to join pranaOS sir so what is the procedure and the requirements are you expecting to join pranaOS

Your truely:
@stevanson

My skillset:
```
python field: 3 years
javascript field: 2.5 years
c field: 2.5 years
c++ field: 2 years
typescript field: 1 year
```

**Comment by krishpranav** [comment]
hi @stevanson 
I have saw your skillset
i will ask you some questions can you answer them in discord under #interview section

**Comment by stevanson** [comment]
ok sir sure can i get the discord link

**Comment by krishpranav** [comment]
yea sure one second

**Comment by stevanson** [comment]
ok sir

**Comment by krishpranav** [comment]
here is the discord link: https://discord.gg/XmpBTmy9Bz

**Comment by stevanson** [comment]
ok sir i will join in a couple of minutes

**Comment by krishpranav** [comment]
ok sure
