### ISSUE TITLE
Hello 👋

### ISSUE THREAD

**Issue by antonystevanson** [pranaOS/pranaOS#56]
hi sir i am a c++ developer can i join pranaOS?

**Comment by krishpranav** [comment]
hi @antonystevanson can you join the pranaOS discord server

**Comment by antonystevanson** [comment]
yea sure can you provide discord link?

**Comment by krishpranav** [comment]
https://discord.gg/XmpBTmy9Bz
join

**Comment by antonystevanson** [comment]
ok sure in a couple of minutes sir
