### ISSUE TITLE
Alex5xt want to join pranaOS

### ISSUE THREAD

**Issue by Alex5xt** [pranaOS/pranaOS#7]
hi krishpranav sir i want to join pranaOS

**Comment by krishpranav** [comment]
hi @Alex5xt so you want to join pranaOS??

**Comment by Alex5xt** [comment]
hi sir

**Comment by krishpranav** [comment]
ok i will ask you a simple question for adding you to pranaOS

**Comment by Alex5xt** [comment]
ok sir

**Comment by krishpranav** [comment]
so how many years experience in c++ you have?

**Comment by Alex5xt** [comment]
1 year sir

**Comment by krishpranav** [comment]
ok i will ask you one simple question

**Comment by Alex5xt** [comment]
ok sir

**Comment by krishpranav** [comment]
so how will you store binary search tree

**Comment by Alex5xt** [comment]
it is easy sir

**Comment by Alex5xt** [comment]
```c++
#include<iostream>
using namespace std;
 
class BSTNode
{
public:
    int Key;
    BSTNode * Left;
    BSTNode * Right;
    BSTNode * Parent;
};
```

**Comment by krishpranav** [comment]
woah fast

**Comment by Alex5xt** [comment]
thanks!

**Comment by krishpranav** [comment]
your selected welcome to pranaOS!!!

**Comment by Alex5xt** [comment]
thanks

**Comment by krishpranav** [comment]
i have sended you email for joining pranaOS

**Comment by Alex5xt** [comment]
ok sir i will join

**Comment by krishpranav** [comment]
join our discord: https://discord.gg/XmpBTmy9Bz

**Comment by Alex5xt** [comment]
ok sir i've accepted
