### ISSUE TITLE
OliviaCE wants to join pranaOS

### ISSUE THREAD

**Issue by OliviaCE** [pranaOS/pranaOS#76]
hi @krishpranav I am a c++ developer and python developer
I just saw your project I am interested in it any instructions to join???

**Comment by krishpranav** [comment]
hi @OliviaCE join discord and you will receive questions under #interview channel

**Comment by OliviaCE** [comment]
ok @krishpranav can you provide the discord link?

**Comment by krishpranav** [comment]
pranaOS discord link: https://discord.gg/XmpBTmy9Bz
