### ISSUE TITLE
Andrew-stew want to join pranaOS

### ISSUE THREAD

**Issue by Andrew-stew** [pranaOS/pranaOS#8]
hi sir i want to join with you guys and help pranaOS to grow can i join with you all.

**Comment by krishpranav** [comment]
hi @Andrew-stew

**Comment by Andrew-stew** [comment]
hi sir

**Comment by krishpranav** [comment]
so you want to join pranaOS right?

**Comment by Andrew-stew** [comment]
yes sir

**Comment by krishpranav** [comment]
so how many years you have experience in c++?

**Comment by Andrew-stew** [comment]
1 - 2 years sir

**Comment by krishpranav** [comment]
ok cool

**Comment by krishpranav** [comment]
ok i will ask you a simple question

**Comment by Andrew-stew** [comment]
ok sir ask

**Comment by krishpranav** [comment]
what is the purpose of llvm used in many c++ projects?

**Comment by Andrew-stew** [comment]
sir llvm is a compiler and toolchain that is used to develop front end for any programming language and back end

**Comment by krishpranav** [comment]
wow cool

**Comment by krishpranav** [comment]
selected!.
Check your mail

**Comment by Andrew-stew** [comment]
thanks sir
