### ISSUE TITLE
terminal & applications crashing

### ISSUE THREAD

**Issue by michaelsmith213** [pranaOS/pranaOS#87]
hi @krishpranav I have builded pranaOS in my macOS machine so I am facing some issues help me to fix it

**Comment by krishpranav** [comment]
hey @michaelsmith213 so have you installed all the tools that I provided in build.md?

**Comment by michaelsmith213** [comment]
yea I have installed all the tools that you provided

**Comment by michaelsmith213** [comment]
any way to fix it?

**Comment by krishpranav** [comment]
hmm I think so you just rm -rf out/

**Comment by krishpranav** [comment]
again ./build.sh

**Comment by michaelsmith213** [comment]
ok I will try it

**Comment by michaelsmith213** [comment]
yea it now working

**Comment by krishpranav** [comment]
ok great

**Comment by michaelsmith213** [comment]
there are many bugs in pranaOS hope you will fix all those in the next version

**Comment by krishpranav** [comment]
yea sure with pleasure

**Comment by michaelsmith213** [comment]
👍 closing
