### ISSUE TITLE
gn -> CMake

### ISSUE THREAD

**Issue by Alex5xt** [pranaOS/pranaOS#88]
hey @krishpranav so this is a feature that I am recommending you that use cmake & ninja for compiling pranaOS instead of gn

**Comment by Alex5xt** [comment]
gn versions are differ but CMake is for multi platforms

**Comment by krishpranav** [comment]
hey @Alex5xt thanks for telling me. I will just replace from gn -> Cmake + Ninja in the next version

**Comment by Alex5xt** [comment]
ok thanks!!

**Comment by Alex5xt** [comment]
closing
