### ISSUE TITLE
workflow needed

### ISSUE THREAD

**Issue by OliviaCE** [pranaOS/pranaOS#89]
hey @krishpranav so can you add a workflow for pranaOS you can use github actions or use
[circleci](https://circleci.com/) or microsoft azure(i this so there is a free license for azure pipeline or azure devops i dont know surely)

**Comment by OliviaCE** [comment]
azure devops: https://azure.microsoft.com/en-in/services/devops/#overview
circleci: https://circleci.com/
or else
github actions

**Comment by krishpranav** [comment]
ok I will just look up all and tell you

**Comment by OliviaCE** [comment]
great!!

**Comment by NukeWilliams** [comment]
having an workflow is a great idea i recommend circleci cause it is simple to setup i dont know anything about microsoft azure devops and i heard that devops is paid.

**Comment by krishpranav** [comment]
@OliviaCE I have just saw the websites that you provided I will create GitHub workflow soon

**Comment by OliviaCE** [comment]
ok that's a great thing hope you will create workflow soon

**Comment by krishpranav** [comment]
sure!
