### ISSUE TITLE
pranaOS is crashing

### ISSUE THREAD

**Issue by NukeWilliams** [pranaOS/pranaOS#91]
hi @krishpranav when I open about app pranaOS is getting crashed can you pls fix it?

**Comment by krishpranav** [comment]
yea I found out fixing it

**Comment by NukeWilliams** [comment]
:+1:

**Comment by krishpranav** [comment]
hey @NukeWilliams I have fixed the bug check it out!

**Comment by krishpranav** [comment]
```
$ git pull
$ cd out/
$ ./all.sh
```

**Comment by NukeWilliams** [comment]
ok let me check ut out

**Comment by NukeWilliams** [comment]
great work @krishpranav !!!

**Comment by krishpranav** [comment]
__THANKS!__

**Comment by NukeWilliams** [comment]
closing #91 issue
