### ISSUE TITLE
Keyboard bug cannot type 

### ISSUE THREAD

**Issue by NukeWilliams** [pranaOS/pranaOS#93]
@krishpranav 

Bug
**I cannot type on the terminal in pranaOS I think so some keyboard bug**

Fix 
Pls fix it as fast as you can cause this affects the next version of pranaOS(leopard)

Waiting eagerly for the leopard version :)

**Comment by krishpranav** [comment]
hey @NukeWilliams soon this bug will be fixed

**Comment by NukeWilliams** [comment]
waiting for that patch...!! :)

**Comment by krishpranav** [comment]
👍🏻

**Comment by krishpranav** [comment]
@NukeWilliams I just patched that bug pls try it by passing this command:
```
git pull
rm -rf out/ mountpoint/
./build.sh
cd out/
./all.sh
```

**Comment by NukeWilliams** [comment]
ok that's a great thing let me just try it out!!

**Comment by NukeWilliams** [comment]
works great!!!! your awesome man

**Comment by NukeWilliams** [comment]
fixing the bugs very fast great!!

**Comment by krishpranav** [comment]
thanks @NukeWilliams

**Comment by NukeWilliams** [comment]
closing #93
