### ISSUE TITLE
cd command broken

### ISSUE THREAD

**Issue by OliviaCE** [pranaOS/pranaOS#96]
hi @krishpranav so I just found this bug while looking around pranaOS

when it enter the command
```
cd / 
```
in pranaOS terminal

it is not switching directory I have no idea I tried to fix it but no success

I don't know correctly whether it is a kernel bug or a terminal issue pls fix this bug 

regards,
Olivia

**Comment by OliviaCE** [comment]
try to fix #96 bug as fast as you can 👍

**Comment by krishpranav** [comment]
hi @OliviaCE thanks for reporting this bug actually I know this already but forget to fix it let me fix it now

**Comment by OliviaCE** [comment]
ok not a problem :) 

> hi @OliviaCE thanks for reporting this bug actually I know this already but forget to fix it let me fix it now

not a problem ;)

**Comment by krishpranav** [comment]
@OliviaCE fixed #96 bug (cd command broken)
https://github.com/pranaOS/pranaOS/commit/f999372586af511a44efd9c7e83394b2afce8e86

**Comment by krishpranav** [comment]
try it by:
```
$ git pull
$ cd out
$ ./all.sh
```

**Comment by OliviaCE** [comment]
oh great thing @krishpranav let me check it out

**Comment by OliviaCE** [comment]
great work!!!

**Comment by krishpranav** [comment]
thanks!!

**Comment by OliviaCE** [comment]
closing #96 issue
