### ISSUE TITLE
#ifndef _LIB_HEADERFILE_H -> #pragma once

### ISSUE THREAD

**Issue by evilbat831** [pranaOS/pranaOS#99]
hey @krishpranav I have saw the coding style you have added in README.md

in there you have mentioned:
- wrong 
```c++
#ifndef someheader
#define someheader

namespace MyNamespace {
}

#endif 
```

- right:
```
#pragma once

namespace MyNamespace {
}
```

so my doubt is in most of your files you have used this format:
```c++
#ifndef  YOURHEADER

// ...

#endif
```

when will you change those into #pragma once

**Comment by krishpranav** [comment]
hey @evilbat831 I was thinking about to change those files will do it thanks for remembering me :)

**Comment by evilbat831** [comment]
no issues 👍 I will also try to help you in these

**Comment by krishpranav** [comment]
yea sure always welcome :)

**Comment by evilbat831** [comment]
ok great I will do my best

**Comment by krishpranav** [comment]
👍🏻

**Comment by OliviaCE** [comment]
actually converting from #ifndef to #pragma once Is a great thing and It is modern

creating headers using ```#ifndef``` is old  ```#pragma once``` is new one so I recommend to change it I hope you will not face any crashes or bugs when you change from #ifndef to #pragma once

**Comment by OliviaCE** [comment]
creating headers using #pragma once will create less chances of bugs, crashes

**Comment by krishpranav** [comment]
yea agree soon as said by @evilbat831 soon will be changed

**Comment by OliviaCE** [comment]
great If I can I will also help

**Comment by krishpranav** [comment]
yea sure

**Comment by OliviaCE** [comment]
:)

**Comment by krishpranav** [comment]
hey @evilbat831 I just converted #ifndef -> #pragma once in all the headers check it out :)

**Comment by evilbat831** [comment]
hey @krishpranav great work man :)

**Comment by krishpranav** [comment]
thanks :)

**Comment by evilbat831** [comment]
pranaOS leopard version will be released at 1 October??

**Comment by krishpranav** [comment]
nah today I am going to release it release date changed

**Comment by evilbat831** [comment]
ohh ok did you announce it through twitter??

**Comment by krishpranav** [comment]
need to

**Comment by evilbat831** [comment]
ok man closing #99 issue
